language: cpp

branches:
  only:
    - master
    - latest-stable
    - coverity_scan
    - gh-pages-dev
    - website-dev

os: linux
dist: xenial

env:
  - PATH=/opt/qt56/bin:/usr/local/opt/qt5/bin:$PATH

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt563-xenial'
    packages:
      - qt56base
      - libgl1-mesa-dev
      - libarchive-dev

script:
  - cd gui/qt/capture ; bash ./get_libpng-apng.sh ; cd ../../../
  - mkdir build
  - cd build
  - qmake ../gui/qt && make -j4
  - cd ../core
  - make clean && make -j4 CPPFLAGS="-DMULTITHREAD" all
  - cd ../tests/autotester
  - make clean && make -j4 CPPFLAGS="-DMULTITHREAD" all

notifications:
  irc:
    channels:
      - "irc.choopa.net#cemu-dev"
    on_success: change
    on_failure: always
    skip_join: true
