language: python

python:
  - "3.6"

before_install:
  - openssl aes-256-cbc -K $encrypted_99e0d4c9a82e_key -iv $encrypted_99e0d4c9a82e_iv -in deploy/id_rsa_travis_deploy_key.enc -out deploy/id_rsa_travis_deploy_key -d
  - sudo apt-get update -qq

script:
  - ./deploy_travisci.sh
