language: cpp

os: linux
dist: xenial

env:
  - PATH=/opt/qt57/bin:/usr/local/opt/qt5/bin:$PATH

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt571-xenial'
    packages:
      - qt57base
      - libgl1-mesa-dev
      - libarchive-dev
      - libsdl2-dev
      - libusb-1.0-0-dev

script:
  - cd gui/qt/capture ; bash ./get_libpng-apng.sh ; cd ../../../
  - mkdir build
  - cd build
  - qmake ../gui/qt && make -j4
  - cd ../core
  - make clean && make -j4 CPPFLAGS="-DMULTITHREAD" all
  - cd ../tests/autotester
  - make clean && make -j4 CPPFLAGS="-DMULTITHREAD -DGLOB_SUPPORT" all
  - cd ../../core
  - make clean && make -j4 all
  - cd ../gui/sdl/
  - make clean && make -j4 all

notifications:
  irc:
    channels:
      - "irc.choopa.net#cemu-dev"
    on_success: change
    on_failure: always
    skip_join: true
