# AppVeyor CI config
environment:
  BINTRAY_API_KEY:
    secure: AGZJlJvqTJR3lySeBoANrPYyWfgLJciSqTZm3/ZEPbUx4dQ9m1fiWGY3RYBGaYOq
  BINTRAY_API_USERNAME:
    secure: QyZ6LhunNhgW3l/1aiGROg==
  GOOGLE_URL_SHORTENER_API_KEY:
    secure: yPv9WtzW+27giJAicFEXGV0KENiee+3+BG2CIOLarbu5wsm7q/h0Ixqsq70CITPi
  QT5_BIN_DIR_DYNAMIC_32: C:\Qt\5.15.0\msvc2019\bin
  QT5_BIN_DIR_DYNAMIC_64: C:\Qt\5.15.0\msvc2019_64\bin
  QT5_BIN_DIR_STATIC_32: C:\Qt\Qt5.15.0-static\bin
  QT5_BIN_DIR_STATIC_64: C:\Qt\Qt5.15.0x64-static\bin

install:
  - git submodule update --init --recursive
  - C:\Python35\Scripts\pip install requests jinja2 irc
  - C:\Python35\python -u gui\qt\deploy-scripts\appveyor_helper.py install

# Leverage vcpkg to install libarchive deps, because we're lazy
# Make sure we set the special VCPKG_PLATFORM_TOOLSET var to v142
# because we build with MSVS 2019 (appveyor project config)
  - cmd: set VCPKG_PLATFORM_TOOLSET=v142

# Update vcpkg to make things work
  - cd "C:\Tools\vcpkg"
  - git fetch
  - git checkout 2020.06
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%

# Install libarchive for all targets
  - vcpkg install libarchive:x86-windows --recurse
  - vcpkg install libarchive:x64-windows --recurse
  - vcpkg install libarchive:x86-windows-static --recurse
  - vcpkg install libarchive:x64-windows-static --recurse

# Install libpng-apng for all targets
  - vcpkg install libpng[core,apng]:x86-windows --recurse
  - vcpkg install libpng[core,apng]:x64-windows --recurse
  - vcpkg install libpng[core,apng]:x86-windows-static --recurse
  - vcpkg install libpng[core,apng]:x64-windows-static --recurse
  
  - md build_32
  - md build_64
  - md build_static_32
  - md build_static_64

# Since we want to use vcpkg, ensure that it's integrated into the
# build environment.
  - cd c:\tools\vcpkg
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

on_success:
  - cd %APPVEYOR_BUILD_FOLDER%
#  - C:\Python35\python -u gui\qt\deploy-scripts\build_status.py SUCCESS

on_failure:
  - cd %APPVEYOR_BUILD_FOLDER%
#  - C:\Python35\python -u gui\qt\deploy-scripts\build_status.py FAILURE

cache:
  - build_state -> appveyor.yml, appveyor.yml.cache
  - c:\tools\vcpkg\installed\ -> appveyor.yml.cache

artifacts:
 - path: deploy\*-win32-release-static*.zip
   name: static_32_release
   type: zip
 
 - path: deploy\*-win64-release-static*.zip
   name: static_64_release
   type: zip

deploy:
  # Required to only send updated stuff to our manually created tag
  # aka don't try to create a new one
  tag: $(appveyor_repo_tag_name)
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: nT2ApY5FbhZtGKrIWzgH9UYsFi/otN56t3fdwusTjo7Gc3pk+L8VMoLf9lbAL+Ol
  artifact: static_32_release,static_64_release
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
