name: Build Windows

on:
  push:
    branches: [ master, feature/github-actions ]
  pull_request:
    branches: [ master, feature/github-actions ]
  release:
    types: [published]

jobs:
  build:
    name: "Build target: ${{ matrix.arch }}-${{ matrix.config }}"
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        config: [Release]
        include:
          - arch: x64
            arch_name: 64-bit
            arch_suffix: "64"
    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install latest CMake
      uses: lukka/get-cmake@359fbae4b163fa01633e6de228fa7f2a31ab1fc7 # latest as of 2023-04-14

    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@abed23940f9d7bc267b0e1a21ee7b699a3794baa # latest as of 2023-04-14
      with:
        vcpkgGitCommitId: 'b08025687f75908191b1e6c67925d46ea0f398dd'

    - name: Build CEmu Qt ${{ matrix.config }} on Windows ${{ matrix.arch_name }}
      uses: lukka/run-cmake@d8897e1de33ed2ec4628ec5acf69861da7c719db # latest as of 2023-01-13
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/gui/qt/CMakeLists.txt'
        configurePreset: '${{ matrix.arch }}-${{ matrix.config }}'
        buildPreset: '${{ matrix.arch }}-${{ matrix.config }}'
      env:
        VCPKG_FORCE_SYSTEM_BINARIES: 1

    - name: Upload ${{ matrix.arch_name }} ${{ matrix.config }} EXE
      uses: actions/upload-artifact@v3
      with:
        name: CEmu_win${{ matrix.arch_suffix }}_master
        path: ${{ github.workspace }}/gui/qt/CEmu.build/${{ matrix.arch }}-${{ matrix.config }}/CEmu.exe

    - name: Prepare binary for release upload
      if: ${{ matrix.config == 'Release' }}
      run: |
        Rename-Item -Path "${{ github.workspace }}/gui/qt/CEmu.build/${{ matrix.arch }}-${{ matrix.config }}/CEmu.exe" -NewName "CEmu-nightly_win${{ matrix.arch_suffix }}-msvc_qt6.exe"

    - name: Update nightly release
      if: ${{ matrix.config == 'Release' && github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
      uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b # latest as of 2023-01-13
      with:
        tag_name: nightly
        prerelease: true
        token: ${{secrets.GITHUB_TOKEN}}
        files: |
          ./gui/qt/CEmu.build/${{ matrix.arch }}-${{ matrix.config }}/CEmu-nightly_win${{ matrix.arch_suffix }}-msvc_qt6.exe
