name: Coverity Scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches: [master]

jobs:
  coverity:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install Linux dependencies (Ubuntu 18.04+)
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install qtbase5-dev qt5-qmake libgl1-mesa-dev libarchive-dev libudev-dev libusb-1.0-0-dev
        
    - name: Prepare build
      run: |
        set -e
        cd gui/qt/capture ; /bin/bash ./get_libpng-apng.sh ; cd ../../../
        mkdir build
        cd build
        qmake ../gui/qt 
    
    - uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        working-directory: "${{ github.workspace }}/build"

